[package]
name = "danbooru-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
indicatif = { version = "0.17.3", features = ["rayon", "tokio"] }
rayon = "1.7.0"
tokio = { version = "1.26.0", features = ["full"] }

